Vagrant.configure("2") do |config|

	# Define base VM
	config.vm.box = "centos/7"	

	# Sync local home dir to /vagrant on the VM
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.synced_folder "/vagrant/synchronized", "/synchronized"

	# Disk size
	#config.disksize.size = "50GB"

	# Define VM:
	config.vm.define "slalomdsvm_snapshot" do |slalomdsvm_snapshot|

		# Do not change the key for the snapshot, it will be changed the first time
		# the exported boxis used
		slalomdsvm_snapshot.ssh.insert_key = false

		slalomdsvm_snapshot.vm.network "private_network", ip: "192.168.33.10"
		
		slalomdsvm_snapshot.vm.provider "virtualbox" do |vb|
			vb.name = "slalomdsvm_snapshot"
			vb.cpus = 4
			vb.memory = 10240

		end
	end
end
