Vagrant.configure("2") do |config|

	# Define the base box to use
	config.vm.box = "centos/7"	

	# Sync local home dir to /vagrant on the VM
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.synced_folder "/vagrant/synchronized", "/synchronized"

	# Disk size
	#config.disksize.size = "50GB"

	# Define VM:
	config.vm.define "slalomdsvm_snapshot" do |slalomdsvm_snapshot|

		# Do not change the ssh key 
		# Makes it easier to package and share the box
		slalomdsvm_snapshot.ssh.insert_key = false

		slalomdsvm_snapshot.vm.network "private_network", ip: "192.168.33.10"
		
		slalomdsvm_snapshot.vm.provider "virtualbox" do |vb|
			vb.name = "slalomdsvm_snapshot"
			vb.cpus = 6
			vb.memory = 10660
		end
	end
end
